### ISSUE TITLE
The error when I run main.py

### ISSUE THREAD

**Issue by Tbyo** [deepdrive/deepdrive#21]
I am run main.py in pycharm.  Ubantu 16.04.
The error is : 

Address successfully parsed 127.0.0.1:9876
Successfully connected to 127.0.0.1:9876
RegisterClientRequest sent
RegisterClientResponse received client id 1 max cams 8 capture res 2048 protocol version 2.0.20180303005949
Client id is 1
Register camera for client 1 227x227 FoV 60 label forward cam 227x227 60 FOV
RegisterCaptureCameraRequest sent
Poll timed out
Waiting for RegisterCaptureCameraResponse, time out
Successfully connected to /tmp/deepdrive_shared_memory with max size of 157286400
Unknown message with type 0 and Size 0 received
2018-08-30 08:41:49,155 - gym_deepdrive.envs.deepdrive_gym_env - ERROR - Failed first step of environment

> **Traceback (most recent call last):
>   File "/home/user/deepdrive/main.py", line 120, in <module>
>     main()
>   File "/home/user/deepdrive/main.py", line 102, in main
>     path_follower=args.path_follower, fps=args.fps)
>   File "/home/user/deepdrive/tensorflow_agent/agent.py", line 288, in run
>     fps=fps)
>   File "/home/user/deepdrive/deepdrive.py", line 31, in start
>     dd_env.connect(cameras, render)
>   File "/home/user/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 662, in connect
>     self._perform_first_step()
>   File "/home/user/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 672, in _perform_first_step
>     raise RuntimeError(error_msg)
> RuntimeError: Failed first step of environment**

UnregisterClientRequest sent

> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/logging/handlers.py", line 71, in emit
>     if self.shouldRollover(record):
>   File "/usr/lib/python3.5/logging/handlers.py", line 185, in shouldRollover
>     self.stream = self._open()
>   File "/usr/lib/python3.5/logging/__init__.py", line 1037, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> NameError: name 'open' is not defined

Call stack:
  File "/home/user/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 512, in __del__
    self.close()
  File "/home/user/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 526, in close
    self.close_sim()
  File "/home/user/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 208, in close_sim
    log.info('Closing sim')
Message: 'Closing sim'
Arguments: ()
   1620K       44K      229K     86.24%
[2018.08.30-12.41.07:327][  0]LogMemory:      32768        75        75        149          231   21852   32640    4768K       32K      863K     82.02%
[2018.08.30-12.41.07:327][  0]LogMemory: 
[2018.08.30-12.41.07:327][  0]LogMemory: 54528K allocated in pools (with 12910K slack and 3511K waste). Efficiency 93.56%
[2018.08.30-12.41.07:327][  0]LogMemory: Allocations 184558 Current / 1160117 Total (in 852 pools)
[2018.08.30-12.41.07:327][  0]LogMemory: 
[2018.08.30-12.41.07:334][  0]LogAIModule: Creating AISystem for world Demonstration
[2018.08.30-12.41.07:335][  0]LogLoad: Game class is 'VehicleGameMode_C'
[2018.08.30-12.41.07:338][  0]LogWorld: Bringing World /Game/TuningCars/Maps/Demonstration.Demonstration up for play (max tick rate 0) at 2018.08.30-08.41.07
[2018.08.30-12.41.07:338][  0]LogDeepDriveCapture: Capture Proxy [CaptureProxy_C /Game/TuningCars/Maps/Demonstration.Demonstration:PersistentLevel.CaptureProxy_54] registered
[2018.08.30-12.41.07:338][  0]LogDeepDriveServer: DeepDriveServer created
[2018.08.30-12.41.07:338][  0]LogDeepDriveConnectionListener: DeepDriveConnectionListener::Run Started
[2018.08.30-12.41.07:338][  0]LogDeepDriveConnectionListener: Listening on 127.0.0.1:9876
[2018.08.30-12.41.07:338][  0]LogDeepDriveServerProxy: Server Proxy [DeepDriveServerProxy_C /Game/TuningCars/Maps/Demonstration.Demonstration:PersistentLevel.DeepDriveServerProxy_366] registered
[2018.08.30-12.41.07:338][  0]LogWorld: Bringing up level for play took: 0.001380
[2018.08.30-12.41.07:339][  0]LogGameMode: Warning - PATHS NOT DEFINED or NO PLAYERSTART with positive rating
[2018.08.30-12.41.07:340][  0]LogGameMode:Display: Match State Changed from EnteringMap to WaitingToStart
[2018.08.30-12.41.07:340][  0]LogGameState: Match State Changed from EnteringMap to WaitingToStart
[2018.08.30-12.41.07:340][  0]LogGameMode:Display: Match State Changed from WaitingToStart to InProgress
[2018.08.30-12.41.07:371][  0]LogLevel: ActivateLevel /Game/TuningCars/Maps/Sublevels/Canyons 1 1 1
[2018.08.30-12.41.07:374][  0]LogSharedMemCaptureSinkComponent: USharedMemCaptureSinkComponent::InitializeComponent
[2018.08.30-12.41.07:374][  0]LogSharedMemCaptureSinkComponent: SharedMemCaptureSinkWorker::SharedMemCaptureSinkWorker
[2018.08.30-12.41.07:374][  0]LogDeepDriveCapture: SharedMemoryImpl_Linux::create Shared mem /tmp/deepdrive_shared_memory with size 157286400 successfully created at 0x7efdeea00000  sizeof bool 1  sizeof 72
[2018.08.30-12.41.07:374][  0]LogDeepDriveCapture: Found sink SharedMemSink
[2018.08.30-12.41.07:375][  0]LogGameState: Match State Changed from WaitingToStart to InProgress
[2018.08.30-12.41.07:375][  0]LogLoad: Took 0.411721 seconds to LoadMap(/Game/TuningCars/Maps/Demonstration)
[2018.08.30-12.41.07:409][  0]LogDeepDriveConnectionListener: DeepDriveConnectionListener::Run Socket is listening T
[2018.08.30-12.41.08:916][  0]LogLoad: (Engine Initialization) Total time: 4.08 seconds
[2018.08.30-12.41.08:916][  0]LogExternalProfiler: No external profilers were discovered.  External profiling features will not be available.
[2018.08.30-12.41.09:577][  2]LogRenderer: Reallocating scene render targets to support 1600x900 NumSamples 1 (Frame:2).
[2018.08.30-12.41.45:397][  2]LogDeepDriveServer: Incoming client connection from 127.0.0.1:50302
[2018.08.30-12.41.45:410][  2]LogBlueprintUserMessages: [AliceGT_C_0] Client 1 registered as Master
[2018.08.30-12.41.45:410][  2]LogDeepDriveClientConnection: [1] Client wants to register reqMaster T isMaster T
[2018.08.30-12.41.45:411][  2]LogDeepDriveClientConnection: [1] Client registered.
[2018.08.30-12.41.46:939][  3]LogDeepDriveCapture: Register CaptureCameraComponent with id 1
[2018.08.30-12.41.46:940][  3]DeepDriveCaptureComponent: Scene capture setup for SceneCaptureComponent_1 at 0x7efe4ca27480
[2018.08.30-12.41.46:940][  3]DeepDriveCaptureComponent: UCaptureCameraComponent::InitializeComponent 0x0x7efe4ca27480 camId 1
[2018.08.30-12.41.46:941][  3]LogDeepDriveServer: Camera registered 1 0
[2018.08.30-12.41.49:313][  4]LogDeepDriveCSuccessfully unregistered
Socket closed
2018-08-30 08:41:49,313 - gym_deepdrive.envs.deepdrive_gym_env - INFO - Closing sim

Process finished with exit code 1

**Comment by crizCraig** [comment]
Sorry we are late on this. Are you able to run the sim on its own? The binary in most likely in `$HOME/Deepdrive/sim` per the dot files in `$HOME/.deepdrive/deepdrive_dir`
