### ISSUE TITLE
 python main.py --baseline --experiment-name my-baseline-test

### ISSUE THREAD

**Issue by ytgcljj** [deepdrive/deepdrive#26]
```launchx-16-500@launchx16500-System-Product-Name:~/github/deepdrive$ python main.py --baseline --experiment-name my-baseline-test
###### ><> ><> PyInit_deepdrive_client <>< <>< ######
2018-11-14 14:24:03.732154: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-11-14 14:24:03.799410: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-14 14:24:03.799717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:01:00.0
totalMemory: 11.93GiB freeMemory: 11.44GiB
2018-11-14 14:24:03.799730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:01:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    main()
  File "main.py", line 102, in main
    path_follower=args.path_follower, fps=args.fps)
  File "/home/launchx-16-500/github/deepdrive/tensorflow_agent/agent.py", line 288, in run
    fps=fps)
  File "/home/launchx-16-500/github/deepdrive/deepdrive.py", line 17, in start
    env = gym.wrappers.Monitor(env, directory=c.GYM_DIR, force=True)
AttributeError: module 'gym' has no attribute 'wrappers'
Exception ignored in: <bound method DeepDriveEnv.__del__ of <gym_deepdrive.envs.deepdrive_gym_env.DeepDriveEnv object at 0x7fc8d7be40b8>>
Traceback (most recent call last):
  File "/home/launchx-16-500/github/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 512, in __del__
    self.close()
  File "/home/launchx-16-500/github/deepdrive/gym_deepdrive/envs/deepdrive_gym_env.py", line 521, in close
    deepdrive_client.release_agent_control(self.client_id)
SystemError: <built-in function release_agent_control> returned a result with an error set```

**Comment by crizCraig** [comment]
Hi @ytgcljj - This error suggests you have the wrong version of gym. 

```
AttributeError: module 'gym' has no attribute 'wrappers'
```
What does `pip freeze` return for you?
