### ISSUE TITLE
eror occur when i run python install.py, need a help！

### ISSUE THREAD

**Issue by xieshangfeiabc** [deepdrive/deepdrive#83]
Thanks！！！

(dd) xiesf@Andy123:/mnt/c/Users/xiesh/deepdrive$ python install.py  # Do not run as sudo! Use Miniconda or virtualenv to install without sudo.
Checking python version...check!
Checking for valid Tensorflow installation

*** Warning: Tensorflow not installed, Tensorflow agents will not be available. HINT: Install Tensorflow or use the python / virtualenv you have it already installed to. If you install, check out our Tensorflow install tips on the README

running command: /home/xiesf/miniconda3/envs/dd/bin/python -m pip install sarge wheel requests boto
Requirement already satisfied: sarge in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (0.1.7.post1)
Requirement already satisfied: wheel in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (0.38.4)
Requirement already satisfied: requests in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (2.31.0)
Requirement already satisfied: boto in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (2.49.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (from requests) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (from requests) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages (from requests) (2.0.7)
Collecting python-gist==0.6.1.dev42
  Cloning git://github.com/deepdrive/gist.git to /tmp/pip-install-cudioze6/python-gist_a352b7b2466446ba8c1d27a7f6606a07
  Running command git clone --filter=blob:none --quiet git://github.com/deepdrive/gist.git /tmp/pip-install-cudioze6/python-gist_a352b7b2466446ba8c1d27a7f6606a07
  fatal: unable to connect to github.com:
  github.com[0: 20.205.243.166]: errno=Connection timed out

  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet git://github.com/deepdrive/gist.git /tmp/pip-install-cudioze6/python-gist_a352b7b2466446ba8c1d27a7f6606a07 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/deepdrive/gist.git /tmp/pip-install-cudioze6/python-gist_a352b7b2466446ba8c1d27a7f6606a07 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

 * Install failed, fix issues below and rerun install.py

Traceback (most recent call last):
  File "install.py", line 237, in <module>
    raise e
  File "install.py", line 233, in <module>
    main()
  File "install.py", line 120, in main
    run_command_with_sarge(f'{py} -m pip install -r {req_filename}')
  File "install.py", line 30, in run_command_with_sarge
    raise RuntimeError('Command failed, see above')
RuntimeError: Command failed, see above

**Comment by xieshangfeiabc** [comment]
I use my phone share the wifi，then new error shows：

 * Install failed, fix issues below and rerun install.py

Traceback (most recent call last):
  File "install.py", line 237, in <module>
    raise e
  File "install.py", line 233, in <module>
    main()
  File "install.py", line 134, in main
    bindings_version = get_latest_valid_bindings()
  File "install.py", line 73, in get_latest_valid_bindings
    bucket = conn.get_bucket('deepdrive')
  File "/home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/home/xiesf/miniconda3/envs/dd/lib/python3.7/site-packages/boto/s3/connection.py", line 553, in head_bucket
    raise err
boto.exception.S3ResponseError: S3ResponseError: 404 Not Found
